all:
	gcc -Wall -g -o test_shmat2.exe test_shmat2.c
	gcc -Wall -g -o test_shmat.exe test_shmat.c
	gcc -Wall -g -o test_shmget.exe test_shmget.c
	
clean:
	rm -f test_shmat2.exe test_shmat.exe test_shmget.exe